# This workflow will build a Java project with Gradle

name: Slimefun Beta Builder

on:
  workflow_call:
  workflow_dispatch:

env:
  TZ: 'Asia/Shanghai'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
      - uses: actions/checkout@v4
      - name: Make gradlew executable
        run: chmod +x gradlew
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: ${{ vars.JAVA_CI_VERSION || 21 }}
          java-package: jdk
          architecture: x64
          cache: gradle
      - name: Apply code formatting
        run: ./gradlew spotlessApply --no-daemon
      - name: Codestyle Check
        run: ./gradlew spotlessCheck --no-daemon
      - name: Build Slimefun
        run: ./gradlew build --no-daemon
      - name: Get build artifact filename
        run: |
          FILENAME=$(find build/libs -maxdepth 1 -type f -name "Slimefun-*.jar" ! -name "*-sources.jar" -printf "%f\n")
          [ -n "$FILENAME" ]
          [ "$(printf "%s\n" "$FILENAME" | wc -l)" -eq 1 ]
          echo "SLIMEFUN_ARTIFACT_NAME=$FILENAME" >> "$GITHUB_ENV"
      - uses: actions/upload-artifact@v7
        name: Upload Beta artifact
        with:
          name: Slimefun Beta Build
          path: build/libs/${{ env.SLIMEFUN_ARTIFACT_NAME }}
      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        if: github.ref_name == 'master'
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "exp"
          prerelease: true
          title: "Slimefun 自动构建版本"
          files: |
            build/libs/${{ env.SLIMEFUN_ARTIFACT_NAME }}
