# This workflow will build a Java project with Gradle

name: Slimefun Dev CI

on:
  workflow_call:
  workflow_dispatch:

env:
  TZ: 'Asia/Shanghai'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Make gradlew executable
        run: chmod +x gradlew
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: ${{ vars.JAVA_CI_VERSION || 21 }}
          java-package: jdk
          architecture: x64
          cache: gradle
      - name: Apply code formatting
        run: ./gradlew spotlessApply --no-daemon
      - name: Publish snapshots
        run: |
          echo "::add-mask::$MAVEN_ACCOUNT"
          echo "::add-mask::$MAVEN_PASSWORD"
          ./gradlew publish -Pversioning.disable --no-daemon
        env:
          MAVEN_ACCOUNT: '${{ vars.MAVEN_ACCOUNT }}'
          MAVEN_PASSWORD: '${{ secrets.MAVEN_PASSWORD }}'
      - name: Build Slimefun
        run: ./gradlew clean build --no-daemon
      - name: Mask Output
        run: |
          echo "::add-mask::$CF_API_TOKEN"
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      - name: Get build artifact filename
        run: |
          FILENAME=$(find build/libs -maxdepth 1 -type f -name "Slimefun-*.jar" ! -name "*-sources.jar" -printf "%f\n")
          [ -n "$FILENAME" ]
          [ "$(printf "%s\n" "$FILENAME" | wc -l)" -eq 1 ]
          echo "SLIMEFUN_ARTIFACT_NAME=$FILENAME" >> "$GITHUB_ENV"
      - name: Upload Build to R2
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: "r2 object put slimefun-dev/${{ env.SLIMEFUN_ARTIFACT_NAME }} --file=./build/libs/${{ env.SLIMEFUN_ARTIFACT_NAME }} --content-type=application/java-archive"
