# This workflow will build a Java project with Gradle

name: Pull Request Checker

on:
  workflow_call:
env:
  TZ: 'Asia/Shanghai'

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      short-commit-hash: ${{ steps.env-setup.outputs.SHORT_COMMIT_HASH }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: ${{ vars.JAVA_CI_VERSION || 21 }}
          java-package: jdk
          architecture: x64
          cache: 'gradle'

      - name: Apply code formatting
        run: ./gradlew spotlessApply --no-daemon

      - name: Codestyle Check
        run: ./gradlew spotlessCheck --no-daemon

      # Setup for the preview build
      - name: Environment Setup
        id: env-setup
        run: |
          SHORT_COMMIT_HASH=$(git rev-parse --short=8 ${{ github.sha }})
          JAR_VERSION="Preview Build #${{ github.event.number }}-$SHORT_COMMIT_HASH"
          echo "SHORT_COMMIT_HASH=$SHORT_COMMIT_HASH" >> "$GITHUB_ENV"
          echo "SHORT_COMMIT_HASH=$SHORT_COMMIT_HASH" >> "$GITHUB_OUTPUT"
          echo "JAR_VERSION=$JAR_VERSION" >> "$GITHUB_ENV"

      - name: Build with Maven
        run: ./gradlew build -PprojectVersion="$JAR_VERSION" --no-daemon

      - name: Upload the artifact
        uses: actions/upload-artifact@v7
        with:
          name: slimefun-${{ github.event.number }}-${{ env.SHORT_COMMIT_HASH }}
          path: 'build/libs/Slimefun-${{ env.JAR_VERSION }}.jar'

  call-workflows:
    needs: [ build ]
    uses: ./.github/workflows/e2e-testing.yml
    with:
      artifact-name: slimefun-${{ github.event.number }}-${{ needs.build.outputs.short-commit-hash }}
